In [2]:
import numpy as np
import numba
import time

In [23]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

def vec():
    c = a @ b
    toc = time.time()
    print(c)

@numba.jit()
def nonvec():
    c = 0
    for i in range(1000000):
        c += a[i] * b[i]
    print(c) 


tic = time.time()
vec()
toc = time.time()
print(f"{1000 * (toc - tic)} [ms]")


tic = time.time()
nonvec()
toc = time.time()
print(f"{1000 * (toc - tic)} [ms]")


250031.01173711888
2.504110336303711 [ms]
250031.0117371189
67.49606132507324 [ms]


In [33]:

A = np.array([
    [56, 0, 4.4, 68],
    [1.2, 104, 52, 8],
    [1.8, 135, 99, 0.9]
])
print(A)

cal = A.sum(axis=0)
print(cal)

percentage = A / cal.reshape(1, 4) * 100
print(percentage)

hoge = A /cal * 100
print(hoge)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [36]:
a = np.random.randn(5, 1)
assert(a.shape == (5,1) )
